name: PHP Unit Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4']

    steps:
    - uses: actions/checkout@v2
    
    - name: Enter in the backend folder
      run: cd backend
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHP ${{ matrix.php }} test suite
      run: composer run-script test
